apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-concept
spec:
  volumes: 
  - name: shared-init-vol
    emptyDir: {}
  initContainers:
  - name: demo-init-ubuntu
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "echo hello from ubuntu-user"]
  - name: demo-init-alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from alpine-user"]
  containers:
  - name: write-date-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
    volumeMounts:
    - name: shared-init-vol
      mountPath: /var/log
  - name: display-date-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-init-vol
      mountPath: /usr/share/nginx/html